#!/bin/bash

SCRIPT_DIR=$(dirname "$0")
cd "$SCRIPT_DIR/.."

echo "Bootstrapping the project"
echo "*** Updating submodules…"
git submodule sync --quiet || exit $?
git submodule update --init || exit $?
git submodule foreach --recursive --quiet "git submodule sync --quiet && git submodule update --init" || exit $?

echo
echo "*** Making sure bundle exists…"
(((which bundle &> /dev/null) && echo "Has bundle, continuing.") || (echo "Does not have bundle, trying to install…" && (gem install bundler || sudo gem install bundler)))
echo
echo "*** Running bundle install…"
bundle install

echo
echo "*** Updating CocoaPods…"
pod install

echo
echo "*** Get the databases"
./Scripts/update_dbs
